routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Http\Request;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


//Rutas con el prefijo dashboard para el módulo administrativo
Route::prefix('dashboard')->namespace('web\dashboard')->group(function() {

    //Rutas para las categorías
    Route::resource('categories', 'CategoryController')->except('destroy');

    //Rutas para las categorías
    Route::resource('tags', 'TagController')->except('destroy');

    //Rutas para los usuarios
    Route::resource('users', 'UserController');
    Route::put('users/restore/{user}', 'UserController@restore')->name('users.restore');
    Route::put('users/delete/{user}', 'UserController@delete')->name('users.delete');
    Route::post('users/images', 'UserController@uploadImage')->name('users.upload.image');
    Route::delete('users/images/{image}', 'UserController@deleteImage')->name('users.delete.image');

    //Rutas para los roles y permisos
    Route::resource('roles', 'RoleController');

    //Rutas para los posts
    Route::resource('posts', 'PostController');
    Route::prefix('posts')->group(function() {
        //Rutas subir una imagen
        Route::post('{post}/image', 'PostController@uploadImage')->name('posts.image');
        //Rutas para los comentarios
        Route::resource('{post}/comments', 'CommentController')->only(['index', 'show', 'destroy']);
    });

    Route::get('paymentmethods/subscriptions/create', 'PaymentMethodController@createSubscription');
    Route::post('paymentmethods/subscriptions', 'PaymentMethodController@storeSubscription');
    Route::get('paymentmethods/subscriptions/show', 'PaymentMethodController@showSubscriptions');
    Route::get('paymentmethods/singlecharges/create', 'PaymentMethodController@createSingleCharge');
    Route::post('paymentmethods/singlecharges', 'PaymentMethodController@storeSingleCharge');
    Route::get('paymentmethods/singlecharges/show', 'PaymentMethodController@showSingleCharge');

});

Auth::routes(['verify' => true]);

Route::get('/home', 'HomeController@index')->name('home');

//Rutas para la web SPA
Route::namespace('web')->name('web.')->group(function() {
    Route::get('/', 'WebController@index')->name('index');
    Route::fallback('WebController@index');
});

app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Storage;
use App\Traits\Voteable;

class Post extends Model
{
    use Voteable;

    protected $fillable = [
        'title', 'slug', 'content', 'category_id', 'status', 'image_url', 'user_id'
    ];

    public function category() {
        return $this->belongsTo('App\Category');
    }

    public function user() {
        return $this->belongsTo('App\User');
    }

    public function image() {
        return $this->belongsTo('App\Image');
    }

    public function comments() {
        return $this->hasMany('App\Comment');
    }

    public function votes() {
        return $this->morphMany('App\Vote', 'voteable');
    }

    public function tags() {
        return $this->belongsToMany('App\Tag');
    }

    public function scopeUserRole($query) {
        $user = auth()->user();
        if(!$user->hasRole('admin') && !$user->hasRole('moderator'))
            return $query->where('user_id',$user->id);
    }

    public function scopeSearch($query, $keyword) {
        if (isset($keyword)) {
            return $query->where('title', 'LIKE', "%$keyword%")
                ->orWhere('content', 'LIKE', "%$keyword%");
        }
    }

    public function scopeSortByCategory($query, $category) {
        if( $category && $category !== 'all' )
            return $query->whereHas('category', function ($q) use ($category) {
                $q->where('title', $category);
            });
    }

    public function setTags($tags) {
        if(array_key_exists('tags', $tags)) $this->tags()->sync($tags['tags']);
        else $this->tags()->detach();
    }

    public function getFullPathImageAttribute() {
        return Storage::url($this->image_url);
    }
}

app/Http/Controllers/api/PostController.php
<?php

namespace App\Http\Controllers\api;

//use App\Http\Controllers\api\ApiResponseController as Controller;
use App\Http\Controllers\Controller;
use App\Http\Resources\PostCollection;
use App\Http\Resources\Post as PostResource;
use App\Post;
use App\Traits\ApiResponse;
use App\Traits\Voteable;
use Illuminate\Http\Request;

class PostController extends Controller
{
    use ApiResponse, Voteable;

    public function __construct()
    {
        $this->middleware('auth:api')->only('vote');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        return new PostCollection(
            Post::orderBy('updated_at', 'DESC')
            ->with(['category', 'tags'])
            ->sortByCategory($request->category)
            ->search($request->search)
            ->where('status', 'posted')
            ->votesCount()
            ->paginate(10)
        );
    }

    public function recents(Request $request) {
        return new PostCollection(
            Post::orderBy('updated_at', 'DESC')
            ->with(['category', 'tags'])
            ->where('status', 'posted')
            ->where('slug', '<>', $request->curren_post)
            ->votesCount()
            ->take(6)
            ->get()
        );
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function show(Request $request, String $slug)
    {
        $user = $request->user('api');
        return new PostResource(
            Post::with(['category', 'tags'])
            ->votesUser($user)
            ->votesCount()
            ->where('slug', $slug)
            ->where('status', 'posted')
            ->firstOrFail()
        );
    }

    public function vote(Request $request, Post $post)
    {
        $this->saveVote($post, $request->type);
        return $this->succesResponse();
    }
}

app/Http/Controllers/web/dashboard/CategoryController.php
<?php

namespace App\Http\Controllers\web\dashboard;

use App\Http\Controllers\Controller;
use App\Category;
use App\Http\Requests\StoreCategory;
use Illuminate\Http\Request;

class CategoryController extends Controller
{
    public function __construct() {
        $this->middleware('auth');
        $this->authorizeResource(Category::class, 'category');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $categories = Category::orderBy('title', 'ASC')->search($request->search)->paginate(5);
        return view('dashboard.category.index', compact('categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('dashboard.category.create', ['category' => new Category()]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreCategory $request)
    {
        $category = Category::create($request->validated());
        return redirect()->route('categories.show', $category)->with('status', 'Categoria creada con exito');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Category $category)
    {
        return view('dashboard.category.show', compact('category'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Category $category)
    {
        return view('dashboard.category.edit', compact('category'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(StoreCategory $request, Category $category)
    {
        $category->update($request->validated());
        return redirect()->route('categories.show', $category)->with('status', 'Categoria actualizada con exito');
    }
}

app/Http/Controllers/web/dashboard/CommentController.php
<?php

namespace App\Http\Controllers\web\dashboard;

use App\Http\Controllers\Controller;
use App\Comment;
use App\Post;
use Illuminate\Http\Request;

class CommentController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
        $this->authorizeResource(Comment::class, 'comment');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Post $post)
    {
        $comments = Comment::where('post_id', $post->id)
            ->with('user')
            ->votesCount()
            ->orderBy('updated_at', 'DESC')
            ->paginate();
        return view('dashboard.comment.index', ['comments' => $comments, 'post' => $post, 'params' => $post]);
    }

    public function show(Post $post, $comment)
    {
        $comment = Comment::votesCount()->find($comment);
        return view('dashboard.comment.show', compact('comment', 'post'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Comment  $comment
     * @return \Illuminate\Http\Response
     */
    public function destroy(Post $post, Comment $comment)
    {
        $comment->delete();
        return redirect()->route('comments.index', $post)->with('status', 'Comentario eliminado correctamente');
    }
}

app/Http/Controllers/web/dashboard/PaymentMethodController.php
<?php

namespace App\Http\Controllers\web\dashboard;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\User;

class PaymentMethodController extends Controller
{
    public function createSubscription() {
        $user = auth()->user('api');
        return view('customers.paymentmethods.subscriptions', ['intent' => $user->createSetupIntent(), 'pk' => config('app.stripe_pk')]);
    }

    public function storeSubscription(Request $request) {
        $user = auth()->user('api');
        $user->addPaymentMethod($request->payment_method);
    }

    public function showSubscriptions() {
        $user = auth()->user('api');
        dd($user->paymentMethods());
    }

    public function createSingleCharge() {
        $user = auth()->user('api');
        return view('customers.paymentmethods.singlecharges', ['pk' => config('app.stripe_pk')]);
    }

    public function storeSingleCharge(Request $request) {
        $user = auth()->user('api');
        $user->charge(5040, $request->id);
    }

    public function showSingleCharges() {
        return view('customers.paymentmethods.subscriptions');
    }
}

app/Http/Controllers/web/dashboard/PostController.php
<?php

namespace App\Http\Controllers\web\dashboard;

use App\Http\Controllers\Controller;
use App\Post;
use App\Image;
use App\Category;
use App\Tag;
use App\Http\Requests\StorePost;
use App\Http\Requests\UpdatePost;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;

class PostController extends Controller
{
    public function __construct() {
        $this->middleware('auth');
        $this->authorizeResource(Post::class, 'post');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $posts = Post::orderBy('created_at', 'DESC')
                ->votesCount()
                ->userRole()
                ->paginate(8);
        return view('dashboard.post.index', compact('posts'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = Category::get(['id', 'title'])->pluck('title', 'id');
        $tags = Tag::get(['id', 'name'])->pluck('name', 'id');
        return view('dashboard.post.create', ['post' => new Post(), 'categories' => $categories, 'tags' => $tags]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StorePost $request)
    {
        $post = Post::create($request->validated());
        $post->user()->associate(auth()->user()->id)->save();
        $post->setTags($request->validated());

        return redirect()->route('posts.show', $post)->with('status', 'Post creado con exito');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($post)
    {
        $post = Post::votesCount()->find($post);
        return view('dashboard.post.show', compact('post'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Post $post)
    {
        $categories = Category::get(['id', 'title'])->pluck('title', 'id');
        $tags = Tag::get(['id', 'name'])->pluck('name', 'id');
        return view('dashboard.post.edit', compact('post', 'categories', 'tags'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdatePost $request, Post $post)
    {
        $post->update($request->validated());
        $post->setTags($request->validated());
        return redirect()->route('posts.show', $post)->with('status', 'Post actualizado con exito');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Post $post)
    {
        $post->delete();
        return redirect()->route('posts.index')->with('status', 'Post eliminado con exito');
    }

    /**
     * Store a new image on storage.
     *
     * @param  int  $post
     * @return \Illuminate\Http\Response
     */
    public function uploadImage(Request $request, Post $post)
    {
        $file = $request->validate([
            'image' => 'required|mimes:jpeg,bmp,png|max:10240' //10 Mb
        ]);

        $url = Storage::putFile("posts/$post->id", $file['image']);

        if ($post->image_url) {
            if (Storage::exists($post->image_url)) {
                Storage::delete($post->image_url);
            }
        }
        $post->image_url = $url;
        $post->save();
        
        return redirect()->route('posts.show', $post)->with('status', 'Imagen guardada correctamente');
    }
}

app/Http/Controllers/web/dashboard/TagController.php
<?php

namespace App\Http\Controllers\web\dashboard;

use App\Http\Controllers\Controller;
use App\Tag;
use App\Http\Requests\StoreTag;
use Illuminate\Http\Request;

class TagController extends Controller
{

    public function __construct() {
        $this->middleware('auth');
        $this->authorizeResource(Tag::class, 'tag');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $tags = Tag::orderBy('name', 'ASC')->search($request->search)->paginate();
        return view('dashboard.tag.index', compact('tags'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('dashboard.tag.create', ['tag' => new Tag()]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreTag $request)
    {
        $tag = Tag::create($request->validated());
        return redirect()->route('tags.show', $tag)->with('status', 'Etiqueta creada con exito');;
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Tag  $tag
     * @return \Illuminate\Http\Response
     */
    public function show(Tag $tag)
    {
        return view('dashboard.tag.show', compact('tag'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Tag  $tag
     * @return \Illuminate\Http\Response
     */
    public function edit(Tag $tag)
    {
        return view('dashboard.tag.edit', compact('tag'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Tag  $tag
     * @return \Illuminate\Http\Response
     */
    public function update(StoreTag $request, Tag $tag)
    {
        $tag->update($request->validated());
        return redirect()->route('tags.show', $tag)->with('status', 'Etiqueta actualizada con exito');;
    }
}

resources/views/dashboard/post/create.blade.php
@extends('layouts.dashboard')
@section('content')
<div class="row justify-content-center">
    <div class="col-sm-8">
        @include('dashboard.partials.header', [
            'title' => 'Crear post',
            'route' => 'posts',
            'view'  => 'index'
        ])
        <form id="post-form" action="{{ route('posts.store') }}" method="POST">
            @csrf
            @include('dashboard.post.partials.form')
        </form>
    </div>
</div>
@endsection

resources/views/dashboard/post/edit.blade.php
@extends('layouts.dashboard')
@section('content')
<div class="row justify-content-center">
    <div class="col-sm-8">
        @include('dashboard.partials.header', ['title' => "Editar $post->title"])
        <form id="post-form" action="{{ route('posts.update', ['post' => $post->id]) }}" method="POST">
            @csrf
            @method('PUT')
            @include('dashboard.post.partials.form')
        </form>
    </div>
</div>
@endsection

resources/views/dashboard/post/index.blade.php
@extends('layouts.dashboard')
@section('content')
<div class="row justify-content-center">
    <div class="col-sm-10">
        <h2>Posts</h2>
        @include('dashboard.partials.state')
        @can('create.posts')
        <a class="btn btn-primary my-2" href="{{ route('posts.create') }}">Crear</a>
        @endcan
        <table class="table">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>Titulo</th>
                    <th>Estado</th>
                    <th>N° de me gusta</th>
                    <th>N° de no me gusta</th>
                </tr>
            </thead>
            <tbody>
                @foreach($posts as $post)
                <tr>
                    <td>{{ $post->id }}</td>
                    <td>{{ $post->title }}</td>
                    <td>{{ $post->status }}</td>
                    <td>{{ $post->likes }}</td>
                    <td>{{ $post->dislikes }}</td>
                    @can('show.posts')
                    <td>
                        <a class="btn btn-secondary" href="{{ route('posts.show', ['post' => $post->id]) }}">Ver</a>
                    </td>
                    @endcan
                    @can('edit.posts')
                    <td>
                        <a class="btn btn-secondary" href="{{ route('posts.edit', ['post' => $post->id]) }}">Editar</a>
                    </td>
                    @endcan
                    @can('delete.posts')
                    <td>
                        <button class="btn btn-danger" type="button" data-toggle="modal" data-target="#confirmDelete" data-id="{{ $post->id }}">Eliminar</button>
                    </td>
                    @endcan
                </tr>
                @endforeach
            </tbody>
        </table>
        {{ $posts->links() }}
    </div>
</div>
@can('delete.posts')
@include('dashboard.partials.confirm-delete', ['route' => 'posts'])
@endcan
@endsection

resources/views/dashboard/post/show.blade.php
@extends('layouts.dashboard')
@section('content')
<div class="row justify-content-center">
    <div class="col-sm-8">
        @include('dashboard.partials.header', [
            'title' => $post->title,
            'route' => 'posts',
            'view'  => 'index'
        ])
        @if($post->image_url)
        <img src="{{ url($post->full_path_image) }}" class="img-fluid py-2" alt="imagen no encontrada">
        @endif
        <div class="form-group">
            <strong>Me gusta:</strong> {{ $post->likes }}
            <strong>No me gusta:</strong> {{ $post->dislikes }}
        </div>
        <div class="form-group">
            <label for="title">Titulo</label>
            <input class="form-control" readonly type="text" id="title" name="title" value="{{ $post->title }}">
        </div>
        <div class="form-group">
            <label for="slug">Url amigable</label>
            <input class="form-control" readonly type="text" id="slug" name="slug" value="{{ $post->slug }}">
        </div>
        <div class="form-group">
            <label for="content">Contenido</label>
            <div class="card">
                <div class="card-body ql-container ql-snow">
                    <div class="ql-editor">
                        {!! $post->content !!}
                    </div>
                </div>
            </div>
        </div>
        <div class="form-group">
            <label for="category_id">Categoria</label>
            <input class="form-control" readonly type="text" id="category_id" name="category_id" value="{{ $post->category->title }}">
        </div>
        <div class="form-group">
            <label for="status">Estado</label>
            <input class="form-control" readonly type="text" id="status" name="status" value="{{ $post->status === 'unposted' ? 'No posteado' : 'Posteado' }}">
        </div>
        <div class="form-group">
            <label for="tags">Etiquetas</label>
            @foreach($post->tags as $tag)
            <span class="badge badge-primary">{{ $tag->name }}</span>
            @endforeach
        </div>
        @can('edit.posts')
        <form action="{{ route('posts.image', ['post' => $post->id]) }}" enctype="multipart/form-data" method="post">
            @csrf
            <div class="form-group">
                <label for="image">Imagen</label>
                <div class="input-group">
                    <div class="custom-file">
                        <input type="file" class="custom-file-input" id="image" name="image" aria-describedby="inputGroupFileAddon01" accept="image/*">
                        <label class="custom-file-label" data-browse="Examinar" for="image">Selecciona un archio</label>
                    </div>
                    <div class="input-group-append">
                        <input class="btn btn-outline-secondary" type="submit" value="Subir">
                    </div>
                </div>
            </div>
        </form>
        <a class="btn btn-primary" href="{{ route('posts.edit', $post) }}">Editar</a>
        @endcan
        @can('show.comments')
        <td>
            <a class="btn btn-secondary" href="{{ route('comments.index', $post) }}">Comentarios</a>
        </td>
        @endcan
        @can('delete.posts')
        <button class="btn btn-danger" type="button" data-toggle="modal" data-target="#confirmDelete" data-id="{{ $post->id }}">Eliminar</button>
        @endcan
    </div>
</div>
@can('delete.posts')
@include('dashboard.partials.confirm-delete', ['route' => 'posts'])
@endcan
@endsection